# Generated by Django 2.0.6 on 2018-07-09 18:48

from django.db import migrations, models
import drfaddons.datatypes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', drfaddons.datatypes.UnixTimestampField(auto_created=True)),
                ('create_date', drfaddons.datatypes.UnixTimestampField(auto_now_add=True)),
                ('name', models.CharField(max_length=254, verbose_name='Unique UserName')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email Address')),
                ('mobile', models.CharField(max_length=15, null=True, verbose_name='Mobile Number')),
            ],
            options={
                'verbose_name': 'Contact Detail',
                'verbose_name_plural': 'Contact Details',
            },
        ),
    ]
