# Generated by Django 2.0.6 on 2018-06-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180620_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'verbose_name': 'Contact Detail', 'verbose_name_plural': 'Contact Details'},
        ),
    ]
