# Generated by Django 2.0.6 on 2018-07-17 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drfaddons.datatypes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', drfaddons.datatypes.UnixTimestampField(auto_created=True)),
                ('create_date', drfaddons.datatypes.UnixTimestampField(auto_now_add=True)),
                ('nickname', models.CharField(max_length=250, verbose_name='Nick Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('accnumber', models.TextField(null=True, verbose_name='Account Number')),
            ],
        ),
        migrations.CreateModel(
            name='BankMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', drfaddons.datatypes.UnixTimestampField(auto_created=True)),
                ('create_date', drfaddons.datatypes.UnixTimestampField(auto_now_add=True)),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Bank Name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', drfaddons.datatypes.UnixTimestampField(auto_created=True)),
                ('create_date', drfaddons.datatypes.UnixTimestampField(auto_now_add=True)),
                ('nickname', models.CharField(max_length=250, verbose_name='Nick Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('vendor', models.CharField(choices=[('V', 'VISA'), ('M', 'MAESTRO'), ('MC', 'MASTER CARD'), ('AMX', 'AMERICAN EXPRESS'), ('R', 'RUPAY')], max_length=5, verbose_name='Card Vendor')),
                ('limit', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Limit on Card')),
                ('statement_date', models.DateField(verbose_name='Date of Statement Generation')),
                ('duedate_duration', models.DurationField(default=20, verbose_name='Duration - Statement Date to Due Date')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='drf_account.BankAccount')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='drf_account.BankMaster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', drfaddons.datatypes.UnixTimestampField(auto_created=True)),
                ('create_date', drfaddons.datatypes.UnixTimestampField(auto_now_add=True)),
                ('nickname', models.CharField(max_length=250, verbose_name='Nick Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('vendor', models.CharField(choices=[('V', 'VISA'), ('M', 'MAESTRO'), ('MC', 'MASTER CARD'), ('AMX', 'AMERICAN EXPRESS'), ('R', 'RUPAY')], max_length=5, verbose_name='Card Vendor')),
                ('free_atmtransaction', models.IntegerField(default=10, verbose_name='Free ATM Transaction')),
                ('free_own_atmtransaction', models.IntegerField(default=5, verbose_name='Free ATM Transaction')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='drf_account.BankAccount')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='drf_account.BankMaster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='drf_account.BankMaster'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='debitcard',
            unique_together={('nickname', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='creditcard',
            unique_together={('nickname', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('nickname', 'created_by')},
        ),
    ]
