# Generated by Django 2.0.5 on 2018-07-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmaster',
            name='aliases',
            field=models.TextField(null=True, verbose_name='Aliases of Bank Name'),
        ),
    ]
