# Generated by Django 2.0.6 on 2018-06-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpvalidation',
            name='type',
            field=models.CharField(choices=[('mobile', 'Mobile Number'), ('email', 'EMail Address')], default='email', max_length=15, verbose_name='EMail/Mobile'),
        ),
    ]
