# Generated by Django 2.0.6 on 2018-06-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180626_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authtransaction',
            options={'verbose_name': 'Auth Transaction', 'verbose_name_plural': 'Auth Transactions'},
        ),
        migrations.AlterModelOptions(
            name='otpvalidation',
            options={'verbose_name': 'OTP Validation', 'verbose_name_plural': 'OTP Validations'},
        ),
        migrations.AlterField(
            model_name='otpvalidation',
            name='type',
            field=models.CharField(choices=[('mobile', 'Mobile Number'), ('email', 'EMail Address')], default='email', max_length=15, verbose_name='EMail/Mobile'),
        ),
    ]
