# Generated by Django 2.0.6 on 2018-06-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180629_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpvalidation',
            name='type',
            field=models.CharField(choices=[('email', 'EMail Address'), ('mobile', 'Mobile Number')], default='email', max_length=15, verbose_name='EMail/Mobile'),
        ),
    ]
