# Generated by Django 2.0.6 on 2018-07-09 18:48

from django.db import migrations, models
import django_custom_modules.db_type


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', django_custom_modules.db_type.UnixTimestampField(auto_created=True)),
                ('create_date', django_custom_modules.db_type.UnixTimestampField(auto_now_add=True)),
                ('token', models.CharField(max_length=254, verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
