# Generated by Django 2.0.6 on 2018-07-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_notification', '0002_fcmtoken_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcmtoken',
            old_name='last_modified',
            new_name='update_date',
        ),
    ]
