exclude: .+/migrations/.+\.py
repos:
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
        - id: black

    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.3.6
      hooks:
        - id: reorder-python-imports

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
        - id: check-yaml
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: debug-statements
        - id: requirements-txt-fixer
