# Generated by Django 2.0.6 on 2018-07-09 18:48

from django.db import migrations, models
import django_custom_modules.db_type


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', django_custom_modules.db_type.UnixTimestampField(auto_created=True)),
                ('create_date', django_custom_modules.db_type.UnixTimestampField(auto_now_add=True)),
                ('category', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=6, verbose_name='Category')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Transaction Detail',
                'verbose_name_plural': 'Transaction Details',
            },
        ),
        migrations.CreateModel(
            name='TransactionModes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', django_custom_modules.db_type.UnixTimestampField(auto_created=True)),
                ('create_date', django_custom_modules.db_type.UnixTimestampField(auto_now_add=True)),
                ('mode', models.CharField(max_length=254, unique=True, verbose_name='Mode of Transfer')),
            ],
            options={
                'verbose_name': 'Transaction Mode',
                'verbose_name_plural': 'Transaction Modes',
            },
        ),
    ]
