# Generated by Django 2.0.6 on 2018-06-26 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_custom_modules.db_type


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_auto_20180620_1032'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', django_custom_modules.db_type.UnixTimestampField(auto_created=True)),
                ('create_date', django_custom_modules.db_type.UnixTimestampField(auto_now_add=True)),
                ('category', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=6)),
                ('transaction_date', models.DateField()),
                ('amount', models.FloatField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.ContactDetails')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionModes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', django_custom_modules.db_type.UnixTimestampField(auto_created=True)),
                ('create_date', django_custom_modules.db_type.UnixTimestampField(auto_now_add=True)),
                ('mode', models.CharField(max_length=254, unique=True, verbose_name='Mode of Transfer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.TransactionModes'),
        ),
    ]
