# Generated by Django 2.0.6 on 2018-07-09 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('contacts', '0002_auto_20180709_1848'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodes',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.ContactDetails'),
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.TransactionModes'),
        ),
    ]
