# Generated by Django 2.0.6 on 2018-06-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='category',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=6, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='transaction_date',
            field=models.DateField(verbose_name='Transaction Date'),
        ),
    ]
