# Generated by Django 2.0.6 on 2018-07-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20180709_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiondetails',
            old_name='last_modified',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='transactionmodes',
            old_name='last_modified',
            new_name='update_date',
        ),
    ]
