# Generated by Django 2.0.6 on 2018-06-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20180626_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
    ]
