# Generated by Django 2.0.6 on 2018-06-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20180626_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiondetails',
            options={'verbose_name': 'Transaction Detail', 'verbose_name_plural': 'Transaction Details'},
        ),
        migrations.AlterModelOptions(
            name='transactionmodes',
            options={'verbose_name': 'Transaction Mode', 'verbose_name_plural': 'Transaction Modes'},
        ),
    ]
