# Generated by Django 2.0.5 on 2018-07-17 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drfaddons.datatypes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20180711_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('update_date', drfaddons.datatypes.UnixTimestampField(auto_created=True)),
                ('create_date', drfaddons.datatypes.UnixTimestampField(auto_now_add=True)),
                ('advance_mode', models.BooleanField(default=False, verbose_name='Advance Mode')),
                ('is_beta', models.BooleanField(default=False, verbose_name='Is Beta User')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
